<a href="https://colab.research.google.com/github/lahirumanulanka/ai-notebooks/blob/main/00_tensor_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Exercises

# 1. Tensor Creation

In [1]:
# Create a tensor of shape (5, 3) filled with random values.
import tensorflow as tf
import numpy as np
random_tensor = tf.random.uniform((5, 3), minval=0, maxval=10, dtype=tf.int32)
print("Random Tensor:\n", random_tensor.numpy())

Random Tensor:
 [[6 0 9]
 [2 1 6]
 [3 5 7]
 [1 7 9]
 [2 4 8]]


In [2]:
# Create a tensor of shape (2, 4) filled with ones.
ones_tensor = tf.ones((2, 4), dtype=tf.float32)
print("Ones Tensor:\n", ones_tensor.numpy())

Ones Tensor:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
# Create a tensor from a list [5, 10, 15, 20].
list_tensor = tf.constant([5, 10, 15, 20], dtype=tf.int32)
print("List Tensor:\n", list_tensor.numpy())

List Tensor:
 [ 5 10 15 20]


In [4]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.
image_tensor = tf.random.uniform((6, 8, 3), minval=0, maxval=255, dtype=tf.int32)
print("Image Tensor Shape:", image_tensor.shape)

Image Tensor Shape: (6, 8, 3)


# 2. Tensor Indexing and Slicing

In [5]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.
tensor_10_to_22 = tf.range(10, 22, dtype=tf.int32)
tensor_10_to_22 = tf.reshape(tensor_10_to_22, (3, 4))
print("Tensor with values from 10 to 22:\n", tensor_10_to_22.numpy())

Tensor with values from 10 to 22:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [6]:
# Access the element at the second row, third column.
element = tensor_10_to_22[1, 2]
print("Element at (1, 2):", element.numpy())

Element at (1, 2): 16


In [7]:
# Print the second row.
second_row = tensor_10_to_22[1, :]
print("Second Row:\n", second_row.numpy())

Second Row:
 [14 15 16 17]


In [8]:
# Print the first two columns.
first_two_columns = tensor_10_to_22[:, :2]
print("First Two Columns:\n", first_two_columns.numpy())

First Two Columns:
 [[10 11]
 [14 15]
 [18 19]]


# 3. Tensor Arithmetic Operations

In [9]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random values.
tensor_a = tf.random.uniform((3, 3), minval=0, maxval=10, dtype=tf.int32)
tensor_b = tf.random.uniform((3, 3), minval=0, maxval=10, dtype=tf.int32)
print("Tensor A:\n", tensor_a.numpy())
print("Tensor B:\n", tensor_b.numpy())

Tensor A:
 [[8 5 3]
 [1 4 7]
 [1 6 4]]
Tensor B:
 [[3 8 2]
 [0 4 3]
 [9 6 6]]


In [10]:
# Perform element-wise addition.
tensor_sum = tf.add(tensor_a, tensor_b)
print("Element-wise Sum:\n", tensor_sum.numpy())

Element-wise Sum:
 [[11 13  5]
 [ 1  8 10]
 [10 12 10]]


In [11]:
# Perform element-wise multiplication.
tensor_product = tf.multiply(tensor_a, tensor_b)
print("Element-wise Product:\n", tensor_product.numpy())

Element-wise Product:
 [[24 40  6]
 [ 0 16 21]
 [ 9 36 24]]


In [12]:
# Subtract tensor_b from tensor_a.
tensor_difference = tf.subtract(tensor_a, tensor_b)
print("Element-wise Difference:\n", tensor_difference.numpy())

Element-wise Difference:
 [[ 5 -3  1]
 [ 1  0  4]
 [-8  0 -2]]


# 4. Tensor Aggregation Operations

In [13]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.
tensor_1_to_9 = tf.range(1, 10, dtype=tf.int32)
tensor_1_to_9 = tf.reshape(tensor_1_to_9, (3, 3))
print("Tensor with values from 1 to 9:\n", tensor_1_to_9.numpy())

Tensor with values from 1 to 9:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Compute the sum of all elements.
tensor_sum_all = tf.reduce_sum(tensor_1_to_9)
print("Sum of all elements:", tensor_sum_all.numpy())

Sum of all elements: 45


In [15]:
# Compute the mean of all elements.
tensor_mean_all = tf.reduce_mean(tensor_1_to_9)
print("Mean of all elements:", tensor_mean_all.numpy())

Mean of all elements: 5


In [16]:
# Find the maximum and minimum values.
tensor_max = tf.reduce_max(tensor_1_to_9)
tensor_min = tf.reduce_min(tensor_1_to_9)
print("Maximum value:", tensor_max.numpy())
print("Minimum value:", tensor_min.numpy())

Maximum value: 9
Minimum value: 1


In [17]:
# Compute the sum along the rows.
tensor_sum_rows = tf.reduce_sum(tensor_1_to_9, axis=1)
print("Sum along rows:\n", tensor_sum_rows.numpy())

Sum along rows:
 [ 6 15 24]


In [18]:
# Compute the mean along the columns.
tensor_mean_columns = tf.reduce_mean(tensor_1_to_9, axis=0)
print("Mean along columns:\n", tensor_mean_columns.numpy())

Mean along columns:
 [4 5 6]


# 5. Tensor Reshaping Operations

In [19]:
# Create a tensor tensor of shape (2, 3, 4) with random values.
tensor = tf.random.uniform((2, 3, 4), minval=0, maxval=10, dtype=tf.int32)
print("Original Tensor:\n", tensor.numpy())

Original Tensor:
 [[[9 8 9 8]
  [3 0 1 8]
  [9 7 9 9]]

 [[1 4 5 3]
  [9 9 4 4]
  [4 6 9 1]]]


In [20]:
# Reshape the tensor to (4, 6).
reshaped_tensor = tf.reshape(tensor, (4, 6))
print("Reshaped Tensor:\n", reshaped_tensor.numpy())

Reshaped Tensor:
 [[9 8 9 8 3 0]
 [1 8 9 7 9 9]
 [1 4 5 3 9 9]
 [4 4 4 6 9 1]]


In [21]:
# Transpose the tensor (swap the first and second dimensions).
transposed_tensor = tf.transpose(tensor, perm=[1, 0, 2])
print("Transposed Tensor:\n", transposed_tensor.numpy())

Transposed Tensor:
 [[[9 8 9 8]
  [1 4 5 3]]

 [[3 0 1 8]
  [9 9 4 4]]

 [[9 7 9 9]
  [4 6 9 1]]]


In [22]:
# Flatten the tensor to a 1D tensor.
flattened_tensor = tf.reshape(tensor, [-1])
print("Flattened Tensor:\n", flattened_tensor.numpy())

Flattened Tensor:
 [9 8 9 8 3 0 1 8 9 7 9 9 1 4 5 3 9 9 4 4 4 6 9 1]


# 6. Tensor Broadcasting

In [23]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.
tensor_a = tf.range(1, 7, dtype=tf.int32)
tensor_a = tf.reshape(tensor_a, (2, 3))
print("Tensor A:\n", tensor_a.numpy())

Tensor A:
 [[1 2 3]
 [4 5 6]]


In [24]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].
tensor_b = tf.constant([1, 2, 3], dtype=tf.int32)
tensor_b = tf.reshape(tensor_b, (1, 3))
print("Tensor B:\n", tensor_b.numpy())

Tensor B:
 [[1 2 3]]


In [26]:
# Perform broadcasting addition.
tensor_sum = tensor_a + tensor_b
print("Broadcasted Sum:\n", tensor_sum.numpy())

Broadcasted Sum:
 [[2 4 6]
 [5 7 9]]


In [27]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].
tensor_c = tf.constant([1, 2, 3], dtype=tf.int32)
tensor_c = tf.reshape(tensor_c, (3, 1))
print("Tensor C:\n", tensor_c.numpy())

Tensor C:
 [[1]
 [2]
 [3]]


In [29]:
# Perform broadcasting multiplication.
tensor_product_matrix = tf.matmul(tensor_a, tensor_c)
print("Matrix Multiplication:\n", tensor_product_matrix.numpy())

Matrix Multiplication:
 [[14]
 [32]]


# 7. Tensor Device Management

In [31]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).
if tf.config.list_physical_devices('GPU'):
    tensor_gpu = tf.random.uniform((3, 3), minval=0, maxval=10, dtype=tf.float32)
    tensor_gpu = tensor_gpu.gpu()
    print("Tensor on GPU:\n", tensor_gpu.numpy())

Tensor on GPU:
 [[4.074789  6.1560383 6.8264556]
 [5.6448374 9.966159  4.081049 ]
 [7.328179  7.2667494 3.6686838]]


In [33]:
# Verify if the tensor is on GPU.
if tf.config.list_physical_devices('GPU'):
    print("Tensor is on GPU.")
else:
    print("Tensor is not on GPU.")
# Move the tensor back to CPU.
tensor_cpu = tensor_gpu.cpu()
print("Tensor on CPU:\n", tensor_cpu.numpy())

Instructions for updating:
Use tf.identity with explicit device placement instead.


Tensor is on GPU.
Tensor on CPU:
 [[4.074789  6.1560383 6.8264556]
 [5.6448374 9.966159  4.081049 ]
 [7.328179  7.2667494 3.6686838]]


# 8. Tensor Cloning and Detaching

In [34]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor.requires_grad = True
print("Original Tensor:\n", tensor.numpy())

Original Tensor:
 [1. 2. 3.]


In [35]:
# Clone the tensor and print the cloned tensor.
cloned_tensor = tf.identity(tensor)
print("Cloned Tensor:\n", cloned_tensor.numpy())

Cloned Tensor:
 [1. 2. 3.]


In [36]:
# Detach the tensor from the computation graph and print the detached tensor.
detached_tensor = tf.stop_gradient(tensor)
print("Detached Tensor:\n", detached_tensor.numpy())

Detached Tensor:
 [1. 2. 3.]


# 9. High Dimensional Tensors

In [37]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.
tensor = tf.random.uniform((2, 3, 4, 5), minval=0, maxval=10, dtype=tf.int32)
print("4D Tensor:\n", tensor.numpy())

4D Tensor:
 [[[[6 2 7 4 4]
   [3 2 3 9 1]
   [1 2 0 3 7]
   [8 9 9 6 1]]

  [[8 4 0 4 1]
   [5 8 9 3 9]
   [4 7 0 7 9]
   [9 5 3 6 7]]

  [[9 9 5 2 1]
   [8 5 2 5 5]
   [2 7 4 2 0]
   [1 5 1 2 6]]]


 [[[6 2 4 7 5]
   [0 5 4 3 8]
   [7 5 8 3 5]
   [9 8 9 2 8]]

  [[8 3 6 6 4]
   [3 6 6 7 0]
   [4 2 2 9 8]
   [8 9 7 2 1]]

  [[6 2 4 4 9]
   [3 6 7 2 1]
   [8 9 7 1 9]
   [5 6 8 4 2]]]]


In [38]:
# Print the shape of the tensor.
print("Shape of the tensor:", tensor.shape)

Shape of the tensor: (2, 3, 4, 5)


In [39]:
# Access the element at position (1, 2, 3, 4).
element = tensor[1, 2, 3, 4]
print("Element at (1, 2, 3, 4):", element.numpy())

Element at (1, 2, 3, 4): 2


In [40]:
# Slice and print the first two elements along the first dimension.
first_two_elements = tensor[:2, :, :, :]
print("First two elements along the first dimension:\n", first_two_elements.numpy())

First two elements along the first dimension:
 [[[[6 2 7 4 4]
   [3 2 3 9 1]
   [1 2 0 3 7]
   [8 9 9 6 1]]

  [[8 4 0 4 1]
   [5 8 9 3 9]
   [4 7 0 7 9]
   [9 5 3 6 7]]

  [[9 9 5 2 1]
   [8 5 2 5 5]
   [2 7 4 2 0]
   [1 5 1 2 6]]]


 [[[6 2 4 7 5]
   [0 5 4 3 8]
   [7 5 8 3 5]
   [9 8 9 2 8]]

  [[8 3 6 6 4]
   [3 6 6 7 0]
   [4 2 2 9 8]
   [8 9 7 2 1]]

  [[6 2 4 4 9]
   [3 6 7 2 1]
   [8 9 7 1 9]
   [5 6 8 4 2]]]]


In [41]:
# Sum all elements in the tensor.
tensor_sum = tf.reduce_sum(tensor)
print("Sum of all elements:", tensor_sum.numpy())

Sum of all elements: 588


In [42]:
# Compute the mean along the third dimension.
tensor_mean = tf.reduce_mean(tensor, axis=2)
print("Mean along the third dimension:\n", tensor_mean.numpy())

Mean along the third dimension:
 [[[4 3 4 5 3]
  [6 6 3 5 6]
  [5 6 3 2 3]]

 [[5 5 6 3 6]
  [5 5 5 6 3]
  [5 5 6 2 5]]]


# 10. Combining Tensor Operations

In [43]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.
tensor_a = tf.random.uniform((2, 3, 4), minval=0, maxval=10, dtype=tf.int32)
tensor_b = tf.random.uniform((2, 3, 4), minval=0, maxval=10, dtype=tf.int32)
print("Tensor A:\n", tensor_a.numpy())
print("Tensor B:\n", tensor_b.numpy())

Tensor A:
 [[[7 6 1 9]
  [0 6 1 9]
  [8 8 9 3]]

 [[8 0 0 3]
  [1 3 9 8]
  [2 9 7 5]]]
Tensor B:
 [[[5 6 8 5]
  [0 7 2 9]
  [4 2 2 2]]

 [[1 8 1 7]
  [6 3 0 9]
  [6 9 6 0]]]


In [44]:
# Add the two tensors.
tensor_sum = tf.add(tensor_a, tensor_b)
print("Element-wise Sum:\n", tensor_sum.numpy())

Element-wise Sum:
 [[[12 12  9 14]
  [ 0 13  3 18]
  [12 10 11  5]]

 [[ 9  8  1 10]
  [ 7  6  9 17]
  [ 8 18 13  5]]]


In [45]:
# Multiply the resulting tensor by 2.
tensor_product = tf.multiply(tensor_sum, 2)
print("Element-wise Product:\n", tensor_product.numpy())

Element-wise Product:
 [[[24 24 18 28]
  [ 0 26  6 36]
  [24 20 22 10]]

 [[18 16  2 20]
  [14 12 18 34]
  [16 36 26 10]]]


In [46]:
# Reshape the tensor to (4, 6).
reshaped_tensor = tf.reshape(tensor_product, (4, 6))
print("Reshaped Tensor:\n", reshaped_tensor.numpy())

Reshaped Tensor:
 [[24 24 18 28  0 26]
 [ 6 36 24 20 22 10]
 [18 16  2 20 14 12]
 [18 34 16 36 26 10]]


In [47]:
# Compute the sum along the columns.
tensor_sum_columns = tf.reduce_sum(reshaped_tensor, axis=0)
print("Sum along columns:\n", tensor_sum_columns.numpy())

Sum along columns:
 [ 66 110  60 104  62  58]


-------------------------------------------- END ----------------------------------------------